version: '3.8'

networks:
  cash_compass_network:
    driver: bridge

services:
  backend:
    container_name: cash_compass_backend
    image: europe-west8-docker.pkg.dev/cashcompass-409018/backend-images/cash-compass-backend:latest
    pull_policy: always
    ports:
      - "3000:3000"
    env_file:
      - ../.env.docker
    networks:
      - cash_compass_network
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    container_name: cash_compass_frontend
    image: europe-west8-docker.pkg.dev/cashcompass-409018/frontend-images/cash-compass-frontend:latest
    pull_policy: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/budget-compass.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/budget-compass.com/privkey.pem:/etc/ssl/private/privkey.pem
    env_file:
      - ../.env.docker
    networks:
      - cash_compass_network
    depends_on:
      - backend
    restart: unless-stopped

  mysql:
    extends:
      file: services.yml
      service: mysql

volumes:
  mysql-data:
