version: '3.8'

services:
  mysql:
    container_name: cash_compass_mysql
    image: mysql:8.2.0
    env_file:
      - ../.env.docker
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    restart: unless-stopped

  backend:
    container_name: cash_compass_backend
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env.docker
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    container_name: cash_compass_frontend
    build:
      context: ../
      dockerfile: apps/cash-compass/Dockerfile
    ports:
      - "4200:4200"
    env_file:
      - ../.env.docker
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:
