version: '3.8'

networks:
  cash_compass_network:
    driver: bridge

services:
  backend:
    container_name: cash_compass_backend
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env.docker
    networks:
      - cash_compass_network
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    container_name: cash_compass_frontend
    build:
      context: ../
      dockerfile: apps/cash-compass/Dockerfile
    ports:
      - "4200:4200"
    env_file:
      - ../.env.docker
    networks:
      - cash_compass_network
    depends_on:
      - backend
    restart: unless-stopped

  mysql:
    extends:
      file: services.yml
      service: mysql

volumes:
    mysql-data:
